### ISSUE TITLE
Дублирование ключа в массиве

### ISSUE THREAD

**Issue by dmitry-kuchura** [HostCMS/hostcms6.free#3]
В файле /modules/shop/delivery/i18n/ru.php дважды используется ключ 'delivery' из-за чего при формировании письма подтягивается не корректное значение "типа доставки". 

Да это используется и для админки по тому изобретение чего либо повлечет за собой некорректную работу модуля в админке.

Нужно исправить. Спасибо!

**Comment by HostCMS** [comment]
Давно исправлено, повторно установите обновление 6.7.5. Если возникнут проблемы с установкой, пожалуйста, обратитесь в поддержку http://www.hostcms.ru/support/
